### ISSUE TITLE
Basic authentication is deprecated?

### ISSUE THREAD

**Issue by MikePanitz-CCC** [zamansky/github-org-explorer#2]
Hello!
I tried using the app and it worked great!  I was able to build it, run the .EXE for my platform (Win/x64) and see the list of the repos in the org for my class.

Afterwards I got an email from GitHub saying the following:
========EMAIL STARTS HERE===============================
Hi @MikePanitz-CCC,

You recently used a password to access an endpoint through the GitHub API using Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) shadow-electorn-starter/1.0.0 Chrome/66.0.3359.181 Electron/3.0.16 Safari/537.36. We will deprecate basic authentication using password to this endpoint soon:

https://api.github.com/user/orgs

We recommend using a personal access token (PAT) with the appropriate scope to access this endpoint instead. Visit https://github.com/settings/tokens for more information.

Thanks,
The GitHub Team
========EMAIL ENDS HERE===============================

I figured that I'd let you know just so that if they disable the basic auth then your Awesome App won't abruptly stop working :)

**Comment by zamansky** [comment]
Thanks - I know.

When I wrote it, I knew it was deprecated but they weren't sending the
emails plus I hadn't figured out how to do oauth with electron.

I'm going to make the change at some point but since I won't get to it for
a while I'm hoping they leave the API as is for at least a bit :-)

Best,
Mike

**Comment by MikeTheGreat** [comment]
I saw your blog post about getting OAuth to work - that's awesome!

(Should this be closed?)
